[workspace]
members = [
    "bindings/python",
    "bindings/native",
    "bindings/node",
    "bindings/rust",
    "benchmarks/comparison",
]
resolver = "2"

[workspace.dependencies]
lean_multisig_api = { git = "https://github.com/kevaundray/leanVM.git", rev = "f4d2270ac0f694da386489452589664105de0829" }

[profile.release]
lto = "thin"
codegen-units = 1
