"""Python bindings for leanVM's safe ``lean_multisig_api`` facade."""

from typing import final

__all__ = [
    "__version__",
    "LeanMultisigError",
    "Claim",
    "ClaimSigners",
    "SecretKey",
    "Signature",
    "MultiClaimProof",
    "setup",
    "aggregate",
    "verified_signers",
    "verify",
    "merge_claims",
    "verified_claims",
    "verify_claims",
]

__version__: str

class LeanMultisigError(Exception): ...

@final
class Claim:
    def __new__(cls, message: bytes, slot: int) -> "Claim": ...
    @property
    def message(self) -> bytes: ...
    @property
    def slot(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self) -> str: ...

@final
class SecretKey:
    @classmethod
    def generate(cls, slot_start: int, slot_end: int) -> "SecretKey": ...
    @classmethod
    def from_seed(cls, seed: bytes, slot_start: int, slot_end: int) -> "SecretKey": ...
    @classmethod
    def from_bytes(cls, data: bytes) -> "SecretKey": ...
    def to_bytes(self) -> bytes: ...
    @property
    def public_key(self) -> bytes: ...
    @property
    def slot_start(self) -> int: ...
    @property
    def slot_end(self) -> int: ...
    def prepare(self, slot: int) -> None: ...
    def sign(self, claim: Claim) -> "Signature": ...

@final
class Signature:
    @classmethod
    def from_bytes(cls, data: bytes, claim: Claim, signers: list[bytes]) -> "Signature": ...
    def to_bytes(self) -> bytes: ...
    @property
    def claim(self) -> Claim: ...
    def __repr__(self) -> str: ...

@final
class ClaimSigners:
    def __new__(cls, claim: Claim, signers: list[bytes]) -> "ClaimSigners": ...
    @property
    def claim(self) -> Claim: ...
    @property
    def signers(self) -> list[bytes]: ...

@final
class MultiClaimProof:
    @classmethod
    def from_bytes(cls, data: bytes, groups: list[ClaimSigners]) -> "MultiClaimProof": ...
    def to_bytes(self) -> bytes: ...

def setup() -> None: ...
def aggregate(signatures: list[Signature], claim: Claim) -> Signature: ...
def verified_signers(signature: Signature, claim: Claim) -> list[bytes]: ...
def verify(signature: Signature, expected_signers: list[bytes], claim: Claim) -> None: ...
def merge_claims(signatures: list[Signature]) -> MultiClaimProof: ...
def verified_claims(proof: MultiClaimProof) -> list[ClaimSigners]: ...
def verify_claims(proof: MultiClaimProof, expected: list[ClaimSigners]) -> None: ...
