/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Claim {
  constructor(message: Buffer, slot: number)
  get message(): Buffer
  get slot(): number
}

export declare class ClaimSigners {
  constructor(claim: Claim, signers: Array<Buffer>)
  get claim(): Claim
  get signers(): Array<Buffer>
}

export declare class MultiClaimProof {
  static fromBytes(data: Buffer, groups: Array<ClaimSigners>): MultiClaimProof
  toBytes(): Buffer
}

export declare class SecretKey {
  toBytes(): Buffer
  get publicKey(): Buffer
  get slotStart(): number
  get slotEnd(): number
  prepare(slot: number): Promise<unknown>
  sign(claim: Claim): Promise<unknown>
}

export declare class Signature {
  static fromBytes(data: Buffer, claim: Claim, signers: Array<Buffer>): Signature
  toBytes(): Buffer
  get claim(): Claim
}

export declare function aggregate(signatures: Array<Signature>, claim: Claim): Promise<unknown>

export declare function generateSecretKey(slotStart: number, slotEnd: number): Promise<unknown>

export declare function mergeClaims(signatures: Array<Signature>): Promise<unknown>

export declare function secretKeyFromBytes(data: Buffer): Promise<unknown>

export declare function secretKeyFromSeed(seed: Buffer, slotStart: number, slotEnd: number): Promise<unknown>

export declare function setup(): Promise<unknown>

export declare function verifiedClaims(proof: MultiClaimProof): Promise<unknown>

export declare function verifiedSigners(signature: Signature, claim: Claim): Promise<unknown>

export declare function verify(signature: Signature, expectedSigners: Array<Buffer>, claim: Claim): void

export declare function verifyClaims(proof: MultiClaimProof, expected: Array<ClaimSigners>): Promise<unknown>
